source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'simple_form'
gem 'haml-rails'
gem 'decent_exposure'
gem 'decent_decoration'
gem 'draper', '~> 1.3'
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'simple_form_object'
gem 'thin'

group :development do
  gem 'pry-rails'
  gem 'spring'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
end
